Cookie = "AWSALB=r1gt3aqrlDiBww9wMa1gEp8oEhZ2wB1KwsVvEbeNgXlhUWwSRjdjBrJkJWdAFZsjcH5ReiGNCxsNdU9s7WPZfXUQCSoHdDDDu8VMCtfvN6MYudlxy3OmsbA/Mx6E; AWSALBCORS=r1gt3aqrlDiBww9wMa1gEp8oEhZ2wB1KwsVvEbeNgXlhUWwSRjdjBrJkJWdAFZsjcH5ReiGNCxsNdU9s7WPZfXUQCSoHdDDDu8VMCtfvN6MYudlxy3OmsbA/Mx6E"
geo_base_url = "https://geolocation.qa.allwyn.zenitech.co.uk/geo-check"
shop_base_url = 'https://fakestoreapi.com/products'
